### PR TITLE
LOOP-1146 Capture recommended bolus with actual user-entered bolus

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-1146
- Add Codable conformance to StoredCarbEntry
- Add bolus related properties to StoredDosingDecision
- Additional tests

### CODE REVIEW

**Comment by darinkrauss** [comment]
LoopWorkspace PR: https://github.com/tidepool-org/LoopWorkspace/pull/277

**Review by nhamming — APPROVED** [review]
LGTM

**Review by rickpasetto — APPROVED** [review]
LGTM

**Review by ps2 — APPROVED** [review]
LGTM!

**Pull request merged**
