### PR TITLE
rename DeviceAlertHandler -> DeviceAlertPresenter

### PR DESCRIPTION
**Pull request by rickpasetto**
Follow-up name change suggested by @ps2

### CODE REVIEW

**Comment by rickpasetto** [comment]
@ps2 There is a corresponding change needed in `Loop`...what's best practice in this case? Should I put in a `typealias` in the meantime so as not to break `Loop`?  Or just coordinate the merges?

**Comment by ps2** [comment]
I think just coordinating merges is fine; I don't see any reason why the out of sync state should last long, since this is a simple rename.

**Review by ps2 — APPROVED** [review]
LGTM! While we're at it, what do you think of `typeIdentifier` -> `alertName`.  And `alertTypeId` -> `alertTypeID`?

**Comment by rickpasetto** [comment]
I'm 👍 for `alertTypeId` -> `alertTypeID`, but I am not a fan of `alertName` for `typeIdentifier`, because the content of this string is opaque, the implementation details of which is up to devices.  For such things I've been using the moniker "identifier".  I first had it as just `identifier` but it seemed not descriptive enough.  Can we please leave it as `typeIdentifier` for now?

**Review by ps2 — APPROVED** [review]
LGTM!

**Pull request merged**
