### PR TITLE
LOOP-1963: Prevent crashing if DismissibleKeyboardTextField needs to become first responder

### PR DESCRIPTION
**Pull request by rickpasetto**
@nhamming I took a crack at another way to fix this.  This simply avoids the crash, because it checks to make sure the `textField` `canBecomeFirstResponder` before calling `becomeFirstResponder()`

### CODE REVIEW

**Review by nhamming — CHANGES_REQUESTED** [review]
I ran this code independent of the `Loop` `rick/LOOP-1963` and it still crashes. 

Also, `.becomeFirstResponder()` already calls `.canBecomeFirstResponder` (unless I have a misunderstanding).

Here, it is suggested to do 
```
if textField.window != nil {
    textField.becomeFirstResponder()
    context.coordinator.didBecomeFirstResponder = true
}
```

This will stop the crash from occurring without the animation delay.

**Comment by rickpasetto** [comment]
@nhamming that's curious, because I did exactly that (it works--no crash) but then I found `canBecomeFirstResponder` and it also doesn't crash for me.  I'll test it again...

**Comment by rickpasetto** [comment]
Strange...looks like it does crash unless you check the `window` property.

**Comment by nhamming** [comment]
> Strange...looks like it does crash unless you check the `window` property.

Correct. :)

**Review by nhamming — APPROVED** [review]
LGTM

**Pull request merged**
