### PR TITLE
[COASTAL-652] adjust IOB and total U font size to fit width

### PR DESCRIPTION
**Pull request by nhamming**
https://tidepool.atlassian.net/browse/COASTAL-652

### CODE REVIEW

**Comment by ps2** [comment]
`adjustsLetterSpacingToFitWidth` is deprecated. Did you look into any other ways to resolve this? What does it look like after the change?  Does adjusting the letter spacing actually fix it?

I'm ok with this if the result is not squished, but I'm a little surprised if this actually fixes the issue.

**Comment by nhamming** [comment]
> `adjustsLetterSpacingToFitWidth` is deprecated. Did you look into any other ways to resolve this? What does it look like after the change? Does adjusting the letter spacing actually fix it?
> 
> I'm ok with this if the result is not squished, but I'm a little surprised if this actually fixes the issue.

There are 2 changes, the `adjustsLetterSpacingToFitWidth` as you noted and `adjustsFontSizeToFit="NO"` being removed. The result is that there is no truncation.

**Comment by ps2** [comment]
Ok, that makes more sense. I tried it out and the truncation is fixed, but it made the timestamp unreadably small. I think we need to find a way to shrink the large value font, but not the timestamp.  Since I have it up, maybe I'll take a quick swing at that.

IMG_6E9F94829AE0-1

**Comment by nhamming** [comment]
> Ok, that makes more sense. I tried it out and the truncation is fixed, but it made the timestamp unreadably small. I think we need to find a way to shrink the large value font, but not the timestamp. Since I have it up, maybe I'll take a quick swing at that.
> 
> IMG_6E9F94829AE0-1

I was considering removing `at` and `since` in the timestamps because they will not localize well and I think they are unneeded.

**Comment by ps2** [comment]
I think the "at" and "since" are carrying some real communication weight; imagine switching them and the meaning of what is being conveyed changes dramatically. 

I looked a little into making the design more adaptable to smaller screens: I like the previous design a little more aesthetically, but this one does remain readable. 

IMG_4609DA22986A-1

**Comment by nhamming** [comment]
@ps2 I'm no designer :) 

My intention of removing `at` and `since` doesn't mean just display a time. For example, `since 12:00 am` could be replaced with `daily` or `today` or something else that could mean only for the period of time starting at 12:00 am.

**Pull request closed without merging**
