### PR TITLE
[LOOP-2554] Detect delayed interaction with onboarding and reset to beginning

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-2554
- Add RawRepresentable conformance to TherapySettings

### CODE REVIEW

**Comment by darinkrauss** [comment]
LW PR for build: https://github.com/tidepool-org/LoopWorkspace/pull/480

**Review by rickpasetto — COMMENTED** [review]
Unit test?
(Also...OOC, why does `TherapySettings` now need to be `RawRepresentable`?)

**Comment by darinkrauss** [comment]
@rickpasetto Added unit tests. Onboarding needs to serialize therapy settings and I intentionally chose to serialize as `RawRepresentable` to be consistent with other data serialized to `UserDefaults`.

**Review by rickpasetto — APPROVED** [review]
LGTM, thanks for adding unit tests, @darinkrauss !  
(FWIW, I prefer to use `Codable` wherever possible, but I understand you're following other patterns...)

**Pull request merged**
