### PR TITLE
Fix HealthKit crash

### PR DESCRIPTION
**Pull request by Camji55**
Screenshot 2023-06-15 at 11 52 16 AM

### CODE REVIEW

**Comment by ps2** [comment]
Could you give more context on this? How is this crash triggered? Who reported it?  And what is the theory on what is causing the crash?  I don't see a problem here, but digging just a bit, I'm starting to wonder about the thread safety of some of the code in HealthStoreUnitCache.

**Comment by Camji55** [comment]
@ps2 of course! 

It happens occasionally after loop is quit -- about 1 in 20 in my experience. I believe Arwain noticed this first and I saw it a few times while pairing with him. Since then, I've been noticing it myself.

My best guess is that crash is caused by `HealthKitSampleStore` getting de-initialized before the async work done in the Task completes which has a reference to `self`. The alternative to weakly capturing `self` here would be to store a local handle on this `Task` and explicitly cancel it in the `deinit` of `HealthKitSampleStore`, though I believe this would prevent the actual `self.log` call from logging.

I'm happy to sit on these changes locally for a while to verify the crash no longer occurs before merging!

I don't believe this crash affects use in production versions of this build because it happens when the app is quit.

**Comment by ps2** [comment]
What do you mean by "after Loop is quit"?  1) the closure passed to Task has a strong reference to self, so it shouldn't be deallocated.  2) this code should run on startup, generally; maybe later on first run.

**Comment by Camji55** [comment]
@ps2 whenever Loop is re-built in Xcode and the app process is stopped. I've also triggered this by force-quitting the app by swiping up.

**Review by ps2 — CHANGES_REQUESTED** [review]
Please hold off on this; because there is already a strong reference here, I don't think changing it to weak and adding a conditional is the right fix; it may change behavior enough to avoid the crash, but something else is probably going on.

**Pull request closed without merging**
