### PR TITLE
[LOOP-1483] Indicate unsupported values in schedule

### PR DESCRIPTION
**Pull request by nhamming**
https://tidepool.atlassian.net/browse/LOOP-1483

### CODE REVIEW

**Review by ps2 — CHANGES_REQUESTED** [review]
As I commented on the other ticket, I think it's best if the PumpManager evaluate the "compatibility" question and offer the user controls to resolve it, during pairing.  It might be that there are more constraints than just whether all the values are supported.

**Comment by nhamming** [comment]
> As I commented on the other ticket, I think it's best if the PumpManager evaluate the "compatibility" question and offer the user controls to resolve it, during pairing. It might be that there are more constraints than just whether all the values are supported.

The pump manager is already providing input on the allowed values. The editor is just respecting this before saving.

**Review by ps2 — APPROVED** [review]
Thanks for the discussion.  I now understand this change works in the context of having PumpManager decide when to present the editor.

**Comment by nhamming** [comment]
> Thanks for the discussion. I now understand this change works in the context of having PumpManager decide when to present the editor.

Thanks! We still need to discuss that more, but maybe when you are back.

**Pull request merged**
