### PR TITLE
LOOP-1810: Change pre-meal guardrail upper bounds to 180

### PR DESCRIPTION
**Pull request by rickpasetto**
Per Brandon, this is a sufficient fix

### CODE REVIEW

**Comment by ps2** [comment]
@rickpasetto I don't think this fixes the crash, though?

**Comment by rickpasetto** [comment]
@ps2 yes, it does.  It means that the spinner now can have a min < max

**Review by nhamming — APPROVED** [review]
LGTM. I'm assuming that `Guardrail.correctionRange.absoluteBounds.lowerBound` must always be lower than `Guardrail.correctionRange.absoluteBounds.upperBound`.

**Comment by rickpasetto** [comment]
@nhamming good question.  Since it is a constant, and since it is a `ClosedRange`, I'd imagine that the app would just crash on startup if someone made lowerBound > upperBound

**Pull request merged**
