### PR TITLE
LOOP-2458 Fix slow status bar update

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-2458
- Add modificationCounter/anchorKey indices to prevent slow data access
- Move settings data decoding from data access queue into utility queue
- Clearly return empty array when store query limit is <= 0

### CODE REVIEW

**Comment by darinkrauss** [comment]
Build LW PR: https://github.com/tidepool-org/LoopWorkspace/pull/411

**Review by nhamming — APPROVED** [review]
LGTM

**Review by ps2 — APPROVED** [review]
LGTM. Am I correct to assume that this may block more than status bar update?  If dataAccessQueue is blocked, *many* other Loop functions will block, like calculating bolus recommendations, updating the forecast, etc.

**Comment by darinkrauss** [comment]
@ps2 Yes, anything that synchronously waits for read or write access to the dosing decisions or settings stores will block. This fixes that.

**Pull request merged**
