### PR TITLE
Fix crashing bug and Core Data managed object context issues

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-2167
- Wrap usage of NSManagedObjectContext extension with perform or performAndWait

### CODE REVIEW

**Comment by darinkrauss** [comment]
LW PR: https://github.com/tidepool-org/LoopWorkspace/pull/334

**Review by nhamming — APPROVED** [review]
LGTM.

[nit] the `addGlucoseSamples` function description uses `newSamples` instead of `samples`.

**Review by ps2 — APPROVED** [review]
LGTM!

**Review by rickpasetto — APPROVED** [review]
LGTM

**Pull request merged**
