### PR TITLE
[LOOP-1431] Allow optional basal delivery state

### PR DESCRIPTION
**Pull request by nhamming**
https://tidepool.atlassian.net/browse/LOOP-1431

make basalDeliveryState optional

### CODE REVIEW

**Review by darinkrauss — APPROVED** [review]
LGTM! 🐴

**Review by darinkrauss — APPROVED** [review]
LGTM! 🚀

**Review by ps2 — CHANGES_REQUESTED** [review]
I don't think there is any semantic difference between a bolus state of none and a bolus state of nil. A PumpManager like those used with pods know that no bolus is being delivered when there is no pod connected, and .none is semantically fine for that. Unless I'm missing some need to differentiate between those. I do understand that *in theory* there could be a case where the PumpManager does not know what the bolus state is, but currently we do not need to represent that state, right?

**Review by ps2 — APPROVED** [review]
LGTM!

**Pull request merged**
