### PR TITLE
LOOP-2542: Change Workout Correction Range absolute minimum from 85 to 87

### PR DESCRIPTION
**Pull request by rickpasetto**
https://tidepool.atlassian.net/browse/LOOP-2542
... to match the Correction Range minimum
LW PR: https://github.com/tidepool-org/LoopWorkspace/pull/384

### CODE REVIEW

**Review by darinkrauss — APPROVED** [review]
LGTM! :rocket:

**Review by darinkrauss — APPROVED** [review]
LGTM! I compared the existing graphics with the graphics in this PR and confirm that the 85 was changed to 87.

**Comment by rickpasetto** [comment]
Thanks @darinkrauss !

**Review by nhamming — COMMENTED** [review]
LGTM

**Pull request merged**
